name: coffee_shop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora/static/Sora-Thin.ttf
        - asset: assets/fonts/Sora/static/Sora-ExtraLight.ttf
        - asset: assets/fonts/Sora/static/Sora-Light.ttf
        - asset: assets/fonts/Sora/static/Sora-Regular.ttf
        - asset: assets/fonts/Sora/static/Sora-Medium.ttf
        - asset: assets/fonts/Sora/static/Sora-SemiBold.ttf
        - asset: assets/fonts/Sora/static/Sora-Bold.ttf
        - asset: assets/fonts/Sora/static/Sora-ExtraBold.ttf